name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Checkout java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Setup-hdfs env
        uses: beyondstorage/setup-hdfs@master
        with:
          hdfs-version: "3.3.2"

      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

  build_all_features:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Checkout python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Checkout java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Setup-hdfs env
        uses: beyondstorage/setup-hdfs@master
        with:
          hdfs-version: "3.3.2"

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Checkout python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Checkout java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Setup-hdfs env
        uses: beyondstorage/setup-hdfs@master
        with:
          hdfs-version: "3.3.2"

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast --features compress,retry
        env:
          RUST_TEST_THREADS: '2'
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
          LD_LIBRARY_PATH: ${{ env.JAVA_HOME }}/lib/server:${{ env.LD_LIBRARY_PATH }}
